baseURL = "https://toozej.github.io/links/"
locale = "en-us"
title = "toozej links"
theme = "LucentLink-Hugo"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]

[params]
  description = "Links for toozej"

[outputs]
  home = ["HTML"]
