server {
    listen 8080;
    server_name _;
    location / {
        proxy_pass http://hugo:1313;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
